# Generated by Django 4.0 on 2022-11-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='schemes'),
        ),
    ]
